server:
  port: 9000

spring:
  application:
    name: ad-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  prefix: /api
  routes:
    sponsor:
      path: /ad-sponsor/**
      service-id: eureka-client-ad-sponsor
      strip-prefix: false
    search:
      path: /ad-search/**
      service-id: eureka-client-ad-search
      strip-prefix: false